version: "3.8"

services:
  hw1-q1-app:
    image: air6011_hw1_q1:latest
    container_name: hw1_q1_app
    command: ["python", "main.py", "-d", "mnist", "-l", "cupy"]
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./result:/app/result
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["0"]
